"""SafeGraph ``top_category`` groupings used in the analysis.

Two schemes are used:
* ``ACTIVITY_GROUPS`` - 5 groups used for the hourly visit series (scripts/06).
* ``FUNCTIONAL_GROUPS`` - 6 functional groups for POI composition (Table S1, scripts/09).
"""
# --- activity groups (hourly visit series) ---
RESTAURANT = [
    'Restaurants and Other Eating Places',
    'Drinking Places (Alcoholic Beverages)',
    'Specialty Food Stores',
    'Special Food Services',
]

SHOPPING = [
    'Grocery Stores',
    'General Merchandise Stores, including Warehouse Clubs and Supercenters',
    'Health and Personal Care Stores',
    'Clothing Stores',
    'Furniture Stores',
    'Sporting Goods, Hobby, and Musical Instrument Stores',
    'Gasoline Stations',
    'Electronics and Appliance Stores',
    'Home Furnishings Stores',
    'Jewelry, Luggage, and Leather Goods Stores',
    'Consumer Goods Rental',
    'Shoe Stores',
    'Automobile Dealers',
    'Automotive Parts, Accessories, and Tire Stores',
    'Department Stores',
    'Other Miscellaneous Store Retailers',
    'Furniture and Home Furnishing Merchant Wholesalers',
    'Book Stores and News Dealers',
    'Office Supplies, Stationery, and Gift Stores',
    'Beer, Wine, and Liquor Stores',
    'Lawn and Garden Equipment and Supplies Stores',
    'Florists',
    'Used Merchandise Stores',
    'Miscellaneous Nondurable Goods Merchant Wholesalers',
    'Grocery and Related Product Merchant Wholesalers',
]

HEALTHCARE = [
    'Offices of Physicians',
    'Offices of Dentists',
    'Offices of Other Health Practitioners',
    'Outpatient Care Centers',
    'Home Health Care Services',
    'General Medical and Surgical Hospitals',
    'Psychiatric and Substance Abuse Hospitals',
    'Specialty (except Psychiatric and Substance Abuse) Hospitals',
    'Nursing Care Facilities (Skilled Nursing Facilities)',
    'Continuing Care Retirement Communities and Assisted Living Facilities for the Elderly',
    'Other Ambulatory Health Care Services',
    'Health and Personal Care Stores',
    'Offices of Mental Health Practitioners (except Physicians)',
    'Personal Care Services',
    'Other Personal Services',
    'Nursing and Residential Care Facilities',
]

EDUCATION = [
    'Elementary and Secondary Schools',
    'Colleges, Universities, and Professional Schools',
    'Technical and Trade Schools',
    'Junior Colleges',
    'Other Schools and Instruction',
    'Educational Support Services',
    'Business Schools and Computer and Management Training',
    'Child Day Care Services',
]

MANUFACTURING = [
    'Management of Companies and Enterprises',
    'Other Miscellaneous Manufacturing',
    'Beverage Manufacturing',
    'Glass and Glass Product Manufacturing',
    'Household Appliance Manufacturing',
    'Other Wood Product Manufacturing',
    'Apparel Accessories and Other Apparel Manufacturing',
    'Motor Vehicle Manufacturing',
    'Electrical Equipment Manufacturing',
    'Architectural and Structural Metals Manufacturing',
    'Residential Building Construction',
    'Hardware Manufacturing',
    'Bakeries and Tortilla Manufacturing',
    'Clay Product and Refractory Manufacturing',
    'Other Food Manufacturing',
    'Other Transportation Equipment Manufacturing',
    'Other Leather and Allied Product Manufacturing',
    'Navigational, Measuring, Electromedical, and Control Instruments Manufacturing',
    'Rubber Product Manufacturing',
    'Metalworking Machinery Manufacturing',
]

ACTIVITY_GROUPS = {
    'Restaurant': RESTAURANT,
    'Shopping': SHOPPING,
    'Healthcare': HEALTHCARE,
    'Education': EDUCATION,
    'Manufacturing': MANUFACTURING,
}

# --- functional groups (POI composition, Table S1) ---
CONSUMER_SERVICES_AND_RETAIL = [
    'Restaurants and Other Eating Places',
    'Drinking Places (Alcoholic Beverages)',
    'Specialty Food Stores',
    'Special Food Services',
    'Grocery Stores',
    'General Merchandise Stores, including Warehouse Clubs and Supercenters',
    'Health and Personal Care Stores',
    'Clothing Stores',
    'Furniture Stores',
    'Automotive Repair and Maintenance',
    'Sporting Goods, Hobby, and Musical Instrument Stores',
    'Gasoline Stations',
    'Electronics and Appliance Stores',
    'Home Furnishings Stores',
    'Jewelry, Luggage, and Leather Goods Stores',
    'Consumer Goods Rental',
    'Shoe Stores',
    'Automobile Dealers',
    'Automotive Parts, Accessories, and Tire Stores',
    'Department Stores',
    'Other Miscellaneous Store Retailers',
    'Furniture and Home Furnishing Merchant Wholesalers',
    'Book Stores and News Dealers',
    'Office Supplies, Stationery, and Gift Stores',
    'Beer, Wine, and Liquor Stores',
    'Lawn and Garden Equipment and Supplies Stores',
    'Florists',
    'Used Merchandise Stores',
    'Miscellaneous Nondurable Goods Merchant Wholesalers',
    'Grocery and Related Product Merchant Wholesalers',
]

HEALTH_AND_EDUCATION = [
    'Offices of Physicians',
    'Offices of Dentists',
    'Offices of Other Health Practitioners',
    'Outpatient Care Centers',
    'Home Health Care Services',
    'General Medical and Surgical Hospitals',
    'Psychiatric and Substance Abuse Hospitals',
    'Specialty (except Psychiatric and Substance Abuse) Hospitals',
    'Nursing Care Facilities (Skilled Nursing Facilities)',
    'Continuing Care Retirement Communities and Assisted Living Facilities for the Elderly',
    'Medical and Diagnostic Laboratories',
    'Other Ambulatory Health Care Services',
    'Health and Personal Care Stores',
    'Offices of Mental Health Practitioners (except Physicians)',
    'Elementary and Secondary Schools',
    'Colleges, Universities, and Professional Schools',
    'Technical and Trade Schools',
    'Junior Colleges',
    'Other Schools and Instruction',
    'Educational Support Services',
    'Business Schools and Computer and Management Training',
    'Child Day Care Services',
    'Personal Care Services',
    'Other Personal Services',
    'Nursing and Residential Care Facilities',
    'Individual and Family Services',
    'Social Advocacy Organizations',
    'Community Food and Housing, and Emergency and Other Relief Services',
    'Social Assistance',
    'Religious Organizations',
]

PRODUCTION_AND_MANUFACTURING = [
    'Management of Companies and Enterprises',
    'Other Miscellaneous Manufacturing',
    'Beverage Manufacturing',
    'Glass and Glass Product Manufacturing',
    'Household Appliance Manufacturing',
    'Other Wood Product Manufacturing',
    'Apparel Accessories and Other Apparel Manufacturing',
    'Motor Vehicle Manufacturing',
    'Electrical Equipment Manufacturing',
    'Architectural and Structural Metals Manufacturing',
    'Residential Building Construction',
    'Hardware Manufacturing',
    'Bakeries and Tortilla Manufacturing',
    'Clay Product and Refractory Manufacturing',
    'Other Food Manufacturing',
    'Other Transportation Equipment Manufacturing',
    'Other Leather and Allied Product Manufacturing',
    'Navigational, Measuring, Electromedical, and Control Instruments Manufacturing',
    'Rubber Product Manufacturing',
    'Machinery, Equipment, and Supplies Merchant Wholesalers',
    'Metalworking Machinery Manufacturing',
    'Chemical and Allied Products Merchant Wholesalers',
    'Household Appliances and Electrical and Electronic Goods Merchant Wholesalers',
    'Metal and Mineral (except Petroleum) Merchant Wholesalers',
    'Petroleum and Petroleum Products Merchant Wholesalers',
    'Steel Product Manufacturing from Purchased Steel',
    'Electronic and Precision Equipment Repair and Maintenance',
    'Printing and Related Support Activities',
]

CONSTRUCTION_AND_INFRASTRUCTURE = [
    'Building Equipment Contractors',
    'Building Finishing Contractors',
    'Foundation, Structure, and Building Exterior Contractors',
    'Building Material and Supplies Dealers',
    'Utility System Construction',
    'Waste Treatment and Disposal',
    'Waste Management and Remediation Services',
    'Lumber and Other Construction Materials Merchant Wholesalers',
    'Hardware, and Plumbing and Heating Equipment and Supplies Merchant Wholesalers',
    'Other Specialty Trade Contractors',
    'Electrical and Electronic Goods Merchant Wholesalers',
    'Commercial and Industrial Machinery and Equipment Rental and Leasing',
    'Coating, Engraving, Heat Treating, and Allied Activities',
    'Services to Buildings and Dwellings',
]

TRANSPORTATION_LOGISTICS_AND_ENERGY = [
    'Couriers and Express Delivery Services',
    'Warehousing and Storage',
    'Support Activities for Road Transportation',
    'Transit and Ground Passenger Transportation',
    'Freight Transportation Arrangement',
    'Electric Power Generation, Transmission and Distribution',
    'Natural Gas Distribution',
    'Water Transportation',
    'Urban Transit Systems',
    'Specialized Freight Trucking',
    'Rail Transportation',
    'Scenic and Sightseeing Transportation',
    'Taxi and Limousine Service',
    'Support Activities for Air Transportation',
    'Petroleum and Petroleum Products Merchant Wholesalers',
    'Electric Power Generation, Transmission and Distribution',
    'Natural Gas Distribution',
    'Water Transportation',
    'Motor Vehicle and Motor Vehicle Parts and Supplies Merchant Wholesalers',
    'Other Transit and Ground Passenger Transportation',
    'Wired and Wireless Telecommunications Carriers',
    'Other Telecommunications',
    'Postal Service',
    'Other Support Activities for Transportation',
]

PROFESSIONAL_SERVICES_AND_PUBLIC_SAFETY = [
    'Legal Services',
    'Accounting, Tax Preparation, Bookkeeping, and Payroll Services',
    'Management, Scientific, and Technical Consulting Services',
    'Architectural, Engineering, and Related Services',
    'Advertising, Public Relations, and Related Services',
    'Employment Services',
    'Business Support Services',
    'Justice, Public Order, and Safety Activities',
    'National Security and International Affairs',
    'Administration of Economic Programs',
    'Administration of Human Resource Programs',
    'Other Professional, Scientific, and Technical Services',
    'Investigation and Security Services',
    'Legal Services',
    'Accounting, Tax Preparation, Bookkeeping, and Payroll Services',
    'Management, Scientific, and Technical Consulting Services',
    'Advertising, Public Relations, and Related Services',
    'Employment Services',
    'Business Support Services',
    'Social Advocacy Organizations',
    'Professional and Commercial Equipment and Supplies Merchant Wholesalers',
    'Data Processing, Hosting, and Related Services',
    'Security and Commodity Contracts Intermediation and Brokerage',
    'Civic and Social Organizations',
    'Other Information Services',
    'Remediation and Other Waste Management Services',
    'Offices of Real Estate Agents and Brokers',
    'Agencies, Brokerages, and Other Insurance Related Activities',
    'Lessors of Real Estate',
    'Activities Related to Credit Intermediation',
    'Activities Related to Real Estate',
    'Insurance Carriers',
    'Automotive Equipment Rental and Leasing',
    'Travel Arrangement and Reservation Services',
    'Death Care Services',
    'Securities and Commodity Contracts Intermediation and Brokerage',
    'Nondepository Credit Intermediation',
    'Other Financial Investment Activities',
    'Motion Picture and Video Industries',
    'Radio and Television Broadcasting',
    'Cable and Other Subscription Programming',
    'Specialized Design Services',
    'Miscellaneous Durable Goods Merchant Wholesalers',
    "Drugs and Druggists' Sundries Merchant Wholesalers",
]

FUNCTIONAL_GROUPS = {
    'Consumer Services and Retail': CONSUMER_SERVICES_AND_RETAIL,
    'Health and Education': HEALTH_AND_EDUCATION,
    'Production and Manufacturing': PRODUCTION_AND_MANUFACTURING,
    'Construction and Infrastructure': CONSTRUCTION_AND_INFRASTRUCTURE,
    'Transportation, Logistics, and Energy': TRANSPORTATION_LOGISTICS_AND_ENERGY,
    'Professional Services and Public Safety': PROFESSIONAL_SERVICES_AND_PUBLIC_SAFETY,
}


def categorize(top_category, groups, default):
    """Return the first group whose list contains ``top_category`` (dict order matters)."""
    for name, members in groups.items():
        if top_category in members:
            return name
    return default
